#pragma kernel CSMain
 
AppendStructuredBuffer<float3> appendBuffer;
 
float size;
float width;
 
[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
 
    //Normalize pos
    float3 pos = id / (width-1);
 
    //make pos range from -size to +size
    pos = (pos - 0.5) * 2.0 * size;
    //keep z pos at 0
    pos.z = 0.0;
    if(id.x % 2 == 0 && id.y % 2 == 0)
        appendBuffer.Append(  pos );
}
